### ISSUE TITLE
Double bonds plot side chain

### ISSUE THREAD

**Issue by dolivierj** [ndcn/soda-ndcn#138]
By default the saturation plot displays info on the first carbon chain. Would be nice to have that as an option that the user can select (1st or 2nd)

**Comment by ajcammack** [comment]
Could this feature be added to the volcano plot as well? As the color coding there still only has the option for the first carbon chain. Also wonder if it is possible to have a third option for "total saturation" with the sum of total double bonds across both chains?

**Comment by dolivierj** [comment]
I will see what I can do.

**Comment by dolivierj** [comment]
Added in Patch 0.6.3, now the user can select carbon chain 1, 2 or the sum of both in the volcano plot and double bonds plot. Chain 2 data for species with only one carbon set was set to 0.
