### ISSUE TITLE
Adjust naming for -log10 p and log2 FC ("logP" to  "- log10 P", "logFC" to "log2 FC" ). Code included

### ISSUE THREAD

**Issue by yassene** [ndcn/soda-ndcn#14]
below is the code to include. We should also put the 10 and 2 in log as subscript for correctness. 

ply1=plot_ly(tmp_res, 
                 x = ~first.carbon, 
                 y = ~first.sat,
                 color = ~logP_q,
                 size = ~logFC_q,
                 # name = ~lipid,
                 # text=~lipid,
                 text=~paste(lipid,'<br>-log10 P:', round(logP,2),'<br>log2 FC:',round(logFC,2)),
                 mode = 'markers',
                 sizes=c(5,40),
                 marker = list(sizemode ='diameter' , opacity = 0.5,sizeref=1),
                 showlegend=T,
                 type = 'scatter'
    ) %>% colorbar(title = "-log10 p")

**Comment by dolivierj** [comment]
Added to volcano plot.
