### ISSUE TITLE
volcano plot comparison order switch

### ISSUE THREAD

**Issue by ajcammack** [ndcn/soda-ndcn#142]
Seems that on volcano plot, the two groups are automatically ordered alphabetically such that the earlier alphabetical group is always on the left and later always on the right. Would be good to be able to switch the direction manually so that either group could be left or right (also for the downloadable table so that the fold-changes are in the desired direction). This is good for if you have many groups you want to compare to a single control, you can always keep the control on the left regardless of the alphabetical order of the groups.

**Comment by dolivierj** [comment]
No idea why this is happening and could not debug. Added a workaround in patch 0.6.5, but now when adding a new plot box, the groups are not displayed by default in the select input.

**Comment by ajcammack** [comment]
I can't seem to download the image files from the volcano now though. When I "download selection" it downloads an empty .csv file

**Comment by ajcammack** [comment]
Nevermind, disregard this. Works to click the photo image. User error, my fault.
