### ISSUE TITLE
dev_mod: special characters

### ISSUE THREAD

**Issue by ricoderks** [ndcn/soda-ndcn#65]
If there are special characters in the group type column, like e.g. ï, the app crashes.

**Comment by dolivierj** [comment]
Cannot recreate, can you provide the metafile?

![image](https://user-images.githubusercontent.com/53037893/219385036-8052c2cf-c9e5-48ec-9539-59e4a4f57edc.png)

**Comment by ricoderks** [comment]
I'll ask Mohan to send you the file. We used the SODA installation on neurolipidatlas.

**Comment by dolivierj** [comment]
Yup tested this on the server too in case there was a weird server problem but it worked for me.

**Comment by dolivierj** [comment]
Actually formatting problem. Special characters should be avoided anyway.
